/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  FaceRecognitionData as PrismaFaceRecognitionData,
} from "@prisma/client";

export class FaceRecognitionDataServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FaceRecognitionDataCountArgs, "select">
  ): Promise<number> {
    return this.prisma.faceRecognitionData.count(args);
  }

  async faceRecognitionDataItems<
    T extends Prisma.FaceRecognitionDataFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FaceRecognitionDataFindManyArgs>
  ): Promise<PrismaFaceRecognitionData[]> {
    return this.prisma.faceRecognitionData.findMany<Prisma.FaceRecognitionDataFindManyArgs>(
      args
    );
  }
  async faceRecognitionData<T extends Prisma.FaceRecognitionDataFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.FaceRecognitionDataFindUniqueArgs>
  ): Promise<PrismaFaceRecognitionData | null> {
    return this.prisma.faceRecognitionData.findUnique(args);
  }
  async createFaceRecognitionData<
    T extends Prisma.FaceRecognitionDataCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FaceRecognitionDataCreateArgs>
  ): Promise<PrismaFaceRecognitionData> {
    return this.prisma.faceRecognitionData.create<T>(args);
  }
  async updateFaceRecognitionData<
    T extends Prisma.FaceRecognitionDataUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FaceRecognitionDataUpdateArgs>
  ): Promise<PrismaFaceRecognitionData> {
    return this.prisma.faceRecognitionData.update<T>(args);
  }
  async deleteFaceRecognitionData<
    T extends Prisma.FaceRecognitionDataDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FaceRecognitionDataDeleteArgs>
  ): Promise<PrismaFaceRecognitionData> {
    return this.prisma.faceRecognitionData.delete(args);
  }
}
